# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

python:
- 2.7

install:
    - pip install -r requirements.txt

script:
    - py.test cv
    - flake8 --exit-zero cv

after_success:
    - coveralls
