# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

python:
- 2.7

before_install:
    - pip install flake8

install:
    - python setup.py install

script:
    - py.test agv_cv
    - flake8 --exit-zero agv_cv
