# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

env:
    - PYTHON=2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    - conda update --yes conda
    - conda create -n testenv --yes pip python=$PYTHON
    - source activate testenv
    # Pillow (or PIL/imaging) is necessary for scipy.misc.imread to exist
    - conda install --yes --quiet numpy scipy imaging
    - pip install pytest pytest-cov
    - pip install flake8

install:
    - python setup.py install

script:
    - py.test --cov agv_cv
    - flake8 --exit-zero agv_cv
after_success:
    - coveralls
